// flow-typed signature: 07f8e50f3def656e074c16d76fcf44f7
// flow-typed version: <<STUB>>/anser_v^1.4.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'anser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "anser" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "anser/lib/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "anser/lib/index.js" {
  declare module.exports: $Exports<"anser/lib/index">;
}
