// flow-typed signature: 6c8f88d8b336468bda2943288fa514ca
// flow-typed version: <<STUB>>/next-redux-wrapper_v^1.3.5/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "next-redux-wrapper" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "next-redux-wrapper/src/index" {
  declare module.exports: any;
}

declare module "next-redux-wrapper/src/index.server.spec" {
  declare module.exports: any;
}

declare module "next-redux-wrapper/src/index.spec" {
  declare module.exports: any;
}

// Filename aliases
declare module "next-redux-wrapper/src/index.js" {
  declare module.exports: $Exports<"next-redux-wrapper/src/index">;
}
declare module "next-redux-wrapper/src/index.server.spec.js" {
  declare module.exports: $Exports<"next-redux-wrapper/src/index.server.spec">;
}
declare module "next-redux-wrapper/src/index.spec.js" {
  declare module.exports: $Exports<"next-redux-wrapper/src/index.spec">;
}
