// flow-typed signature: defba76b367a7b91035713f20b2feab5
// flow-typed version: <<STUB>>/rc-menu_v6.2.6/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rc-menu" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "rc-menu/es/Divider" {
  declare module.exports: any;
}

declare module "rc-menu/es/DOMWrap" {
  declare module.exports: any;
}

declare module "rc-menu/es/index" {
  declare module.exports: any;
}

declare module "rc-menu/es/Menu" {
  declare module.exports: any;
}

declare module "rc-menu/es/MenuItem" {
  declare module.exports: any;
}

declare module "rc-menu/es/MenuItemGroup" {
  declare module.exports: any;
}

declare module "rc-menu/es/MenuMixin" {
  declare module.exports: any;
}

declare module "rc-menu/es/placements" {
  declare module.exports: any;
}

declare module "rc-menu/es/SubMenu" {
  declare module.exports: any;
}

declare module "rc-menu/es/SubPopupMenu" {
  declare module.exports: any;
}

declare module "rc-menu/es/util" {
  declare module.exports: any;
}

declare module "rc-menu/lib/Divider" {
  declare module.exports: any;
}

declare module "rc-menu/lib/DOMWrap" {
  declare module.exports: any;
}

declare module "rc-menu/lib/index" {
  declare module.exports: any;
}

declare module "rc-menu/lib/Menu" {
  declare module.exports: any;
}

declare module "rc-menu/lib/MenuItem" {
  declare module.exports: any;
}

declare module "rc-menu/lib/MenuItemGroup" {
  declare module.exports: any;
}

declare module "rc-menu/lib/MenuMixin" {
  declare module.exports: any;
}

declare module "rc-menu/lib/placements" {
  declare module.exports: any;
}

declare module "rc-menu/lib/SubMenu" {
  declare module.exports: any;
}

declare module "rc-menu/lib/SubPopupMenu" {
  declare module.exports: any;
}

declare module "rc-menu/lib/util" {
  declare module.exports: any;
}

// Filename aliases
declare module "rc-menu/es/Divider.js" {
  declare module.exports: $Exports<"rc-menu/es/Divider">;
}
declare module "rc-menu/es/DOMWrap.js" {
  declare module.exports: $Exports<"rc-menu/es/DOMWrap">;
}
declare module "rc-menu/es/index.js" {
  declare module.exports: $Exports<"rc-menu/es/index">;
}
declare module "rc-menu/es/Menu.js" {
  declare module.exports: $Exports<"rc-menu/es/Menu">;
}
declare module "rc-menu/es/MenuItem.js" {
  declare module.exports: $Exports<"rc-menu/es/MenuItem">;
}
declare module "rc-menu/es/MenuItemGroup.js" {
  declare module.exports: $Exports<"rc-menu/es/MenuItemGroup">;
}
declare module "rc-menu/es/MenuMixin.js" {
  declare module.exports: $Exports<"rc-menu/es/MenuMixin">;
}
declare module "rc-menu/es/placements.js" {
  declare module.exports: $Exports<"rc-menu/es/placements">;
}
declare module "rc-menu/es/SubMenu.js" {
  declare module.exports: $Exports<"rc-menu/es/SubMenu">;
}
declare module "rc-menu/es/SubPopupMenu.js" {
  declare module.exports: $Exports<"rc-menu/es/SubPopupMenu">;
}
declare module "rc-menu/es/util.js" {
  declare module.exports: $Exports<"rc-menu/es/util">;
}
declare module "rc-menu/lib/Divider.js" {
  declare module.exports: $Exports<"rc-menu/lib/Divider">;
}
declare module "rc-menu/lib/DOMWrap.js" {
  declare module.exports: $Exports<"rc-menu/lib/DOMWrap">;
}
declare module "rc-menu/lib/index.js" {
  declare module.exports: $Exports<"rc-menu/lib/index">;
}
declare module "rc-menu/lib/Menu.js" {
  declare module.exports: $Exports<"rc-menu/lib/Menu">;
}
declare module "rc-menu/lib/MenuItem.js" {
  declare module.exports: $Exports<"rc-menu/lib/MenuItem">;
}
declare module "rc-menu/lib/MenuItemGroup.js" {
  declare module.exports: $Exports<"rc-menu/lib/MenuItemGroup">;
}
declare module "rc-menu/lib/MenuMixin.js" {
  declare module.exports: $Exports<"rc-menu/lib/MenuMixin">;
}
declare module "rc-menu/lib/placements.js" {
  declare module.exports: $Exports<"rc-menu/lib/placements">;
}
declare module "rc-menu/lib/SubMenu.js" {
  declare module.exports: $Exports<"rc-menu/lib/SubMenu">;
}
declare module "rc-menu/lib/SubPopupMenu.js" {
  declare module.exports: $Exports<"rc-menu/lib/SubPopupMenu">;
}
declare module "rc-menu/lib/util.js" {
  declare module.exports: $Exports<"rc-menu/lib/util">;
}
