// flow-typed signature: 9840310ab11356f9e494ab17461a93e0
// flow-typed version: <<STUB>>/remark-stringify_v^5.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "remark-stringify" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "remark-stringify/lib/compiler" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/defaults" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/escape" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/macro/all" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/macro/block" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/macro/compile" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/macro/one" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/macro/ordered-items" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/macro/unordered-items" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/set-options" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/copy-identifier-encoding" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/enclose-title" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/enclose-uri" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/enter-link-reference" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/entity-prefix-length" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/label" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/pad" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/util/returner" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/blockquote" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/break" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/code" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/definition" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/delete" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/emphasis" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/footnote-definition" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/footnote-reference" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/footnote" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/heading" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/html" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/image-reference" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/image" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/inline-code" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/link-reference" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/link" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/list-item" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/list" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/paragraph" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/root" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/strong" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/table-cell" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/table" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/text" {
  declare module.exports: any;
}

declare module "remark-stringify/lib/visitors/thematic-break" {
  declare module.exports: any;
}

// Filename aliases
declare module "remark-stringify/index" {
  declare module.exports: $Exports<"remark-stringify">;
}
declare module "remark-stringify/index.js" {
  declare module.exports: $Exports<"remark-stringify">;
}
declare module "remark-stringify/lib/compiler.js" {
  declare module.exports: $Exports<"remark-stringify/lib/compiler">;
}
declare module "remark-stringify/lib/defaults.js" {
  declare module.exports: $Exports<"remark-stringify/lib/defaults">;
}
declare module "remark-stringify/lib/escape.js" {
  declare module.exports: $Exports<"remark-stringify/lib/escape">;
}
declare module "remark-stringify/lib/macro/all.js" {
  declare module.exports: $Exports<"remark-stringify/lib/macro/all">;
}
declare module "remark-stringify/lib/macro/block.js" {
  declare module.exports: $Exports<"remark-stringify/lib/macro/block">;
}
declare module "remark-stringify/lib/macro/compile.js" {
  declare module.exports: $Exports<"remark-stringify/lib/macro/compile">;
}
declare module "remark-stringify/lib/macro/one.js" {
  declare module.exports: $Exports<"remark-stringify/lib/macro/one">;
}
declare module "remark-stringify/lib/macro/ordered-items.js" {
  declare module.exports: $Exports<"remark-stringify/lib/macro/ordered-items">;
}
declare module "remark-stringify/lib/macro/unordered-items.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/macro/unordered-items"
  >;
}
declare module "remark-stringify/lib/set-options.js" {
  declare module.exports: $Exports<"remark-stringify/lib/set-options">;
}
declare module "remark-stringify/lib/util/copy-identifier-encoding.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/util/copy-identifier-encoding"
  >;
}
declare module "remark-stringify/lib/util/enclose-title.js" {
  declare module.exports: $Exports<"remark-stringify/lib/util/enclose-title">;
}
declare module "remark-stringify/lib/util/enclose-uri.js" {
  declare module.exports: $Exports<"remark-stringify/lib/util/enclose-uri">;
}
declare module "remark-stringify/lib/util/enter-link-reference.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/util/enter-link-reference"
  >;
}
declare module "remark-stringify/lib/util/entity-prefix-length.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/util/entity-prefix-length"
  >;
}
declare module "remark-stringify/lib/util/label.js" {
  declare module.exports: $Exports<"remark-stringify/lib/util/label">;
}
declare module "remark-stringify/lib/util/pad.js" {
  declare module.exports: $Exports<"remark-stringify/lib/util/pad">;
}
declare module "remark-stringify/lib/util/returner.js" {
  declare module.exports: $Exports<"remark-stringify/lib/util/returner">;
}
declare module "remark-stringify/lib/visitors/blockquote.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/blockquote">;
}
declare module "remark-stringify/lib/visitors/break.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/break">;
}
declare module "remark-stringify/lib/visitors/code.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/code">;
}
declare module "remark-stringify/lib/visitors/definition.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/definition">;
}
declare module "remark-stringify/lib/visitors/delete.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/delete">;
}
declare module "remark-stringify/lib/visitors/emphasis.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/emphasis">;
}
declare module "remark-stringify/lib/visitors/footnote-definition.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/visitors/footnote-definition"
  >;
}
declare module "remark-stringify/lib/visitors/footnote-reference.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/visitors/footnote-reference"
  >;
}
declare module "remark-stringify/lib/visitors/footnote.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/footnote">;
}
declare module "remark-stringify/lib/visitors/heading.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/heading">;
}
declare module "remark-stringify/lib/visitors/html.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/html">;
}
declare module "remark-stringify/lib/visitors/image-reference.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/visitors/image-reference"
  >;
}
declare module "remark-stringify/lib/visitors/image.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/image">;
}
declare module "remark-stringify/lib/visitors/inline-code.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/inline-code">;
}
declare module "remark-stringify/lib/visitors/link-reference.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/visitors/link-reference"
  >;
}
declare module "remark-stringify/lib/visitors/link.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/link">;
}
declare module "remark-stringify/lib/visitors/list-item.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/list-item">;
}
declare module "remark-stringify/lib/visitors/list.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/list">;
}
declare module "remark-stringify/lib/visitors/paragraph.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/paragraph">;
}
declare module "remark-stringify/lib/visitors/root.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/root">;
}
declare module "remark-stringify/lib/visitors/strong.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/strong">;
}
declare module "remark-stringify/lib/visitors/table-cell.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/table-cell">;
}
declare module "remark-stringify/lib/visitors/table.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/table">;
}
declare module "remark-stringify/lib/visitors/text.js" {
  declare module.exports: $Exports<"remark-stringify/lib/visitors/text">;
}
declare module "remark-stringify/lib/visitors/thematic-break.js" {
  declare module.exports: $Exports<
    "remark-stringify/lib/visitors/thematic-break"
  >;
}
