// flow-typed signature: f36e1850aa615cbc0ac764744c410498
// flow-typed version: <<STUB>>/tv4_v^1.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tv4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "tv4" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "tv4/lang/de" {
  declare module.exports: any;
}

declare module "tv4/lang/es" {
  declare module.exports: any;
}

declare module "tv4/lang/fr" {
  declare module.exports: any;
}

declare module "tv4/lang/nb" {
  declare module.exports: any;
}

declare module "tv4/lang/pl-PL" {
  declare module.exports: any;
}

declare module "tv4/lang/pt-PT" {
  declare module.exports: any;
}

declare module "tv4/lang/sv-SE" {
  declare module.exports: any;
}

declare module "tv4/lang/zh-CN" {
  declare module.exports: any;
}

declare module "tv4/tv4.async-jquery" {
  declare module.exports: any;
}

declare module "tv4/tv4" {
  declare module.exports: any;
}

// Filename aliases
declare module "tv4/lang/de.js" {
  declare module.exports: $Exports<"tv4/lang/de">;
}
declare module "tv4/lang/es.js" {
  declare module.exports: $Exports<"tv4/lang/es">;
}
declare module "tv4/lang/fr.js" {
  declare module.exports: $Exports<"tv4/lang/fr">;
}
declare module "tv4/lang/nb.js" {
  declare module.exports: $Exports<"tv4/lang/nb">;
}
declare module "tv4/lang/pl-PL.js" {
  declare module.exports: $Exports<"tv4/lang/pl-PL">;
}
declare module "tv4/lang/pt-PT.js" {
  declare module.exports: $Exports<"tv4/lang/pt-PT">;
}
declare module "tv4/lang/sv-SE.js" {
  declare module.exports: $Exports<"tv4/lang/sv-SE">;
}
declare module "tv4/lang/zh-CN.js" {
  declare module.exports: $Exports<"tv4/lang/zh-CN">;
}
declare module "tv4/tv4.async-jquery.js" {
  declare module.exports: $Exports<"tv4/tv4.async-jquery">;
}
declare module "tv4/tv4.js" {
  declare module.exports: $Exports<"tv4/tv4">;
}
