// flow-typed signature: 8e95b19742d09c8dfb7f95dd98769d58
// flow-typed version: <<STUB>>/xhr2_v*/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xhr2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "xhr2" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "xhr2/lib/browser" {
  declare module.exports: any;
}

declare module "xhr2/lib/xhr2" {
  declare module.exports: any;
}

// Filename aliases
declare module "xhr2/lib/browser.js" {
  declare module.exports: $Exports<"xhr2/lib/browser">;
}
declare module "xhr2/lib/xhr2.js" {
  declare module.exports: $Exports<"xhr2/lib/xhr2">;
}
